com.akb.dao.application:
  connectionString: mongodb://localhost:27017/aop
  
com.akb.dao.application.event:
  connectionString: mongodb://localhost:27017/aop
  
com.akb.core.kafka:
  servers: 127.0.0.1:9092
  groupId: 1
  topics:
    applicationlog: applicationlog
    dms: dms
    thirdpartycall: thirdpartycall
    ews: ews
    email: email
    
kafka.topicName: dms

application-dao-service-url: http://localhost:3000/applications