//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 02:14:29 PM EDT 
//


package com.akb.ws.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EWSREsponse" type="{http://ws.akb.com/ews}EWSResponseDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ewsrEsponse"
})
@XmlRootElement(name = "EWSResponse")
public class EWSResponse {

    @XmlElement(name = "EWSREsponse", required = true)
    protected EWSResponseDetails ewsrEsponse;

    /**
     * Gets the value of the ewsrEsponse property.
     * 
     * @return
     *     possible object is
     *     {@link EWSResponseDetails }
     *     
     */
    public EWSResponseDetails getEWSREsponse() {
        return ewsrEsponse;
    }

    /**
     * Sets the value of the ewsrEsponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EWSResponseDetails }
     *     
     */
    public void setEWSREsponse(EWSResponseDetails value) {
        this.ewsrEsponse = value;
    }

}
