//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 02:14:29 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.akb.com/ews", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akb.ws.ews;
